CREATE OR REPLACE PROCEDURE DSQL
AS
  TYPE EMP_TYPE IS TABLE OF EMP.ENAME%TYPE;
  EMP_TABLE EMP_TYPE;
  v_SQL     varchar2(50) := 'SELECT ENAME FROM EMP';
Begin
   EXECUTE IMMEDIATE(v_SQL)
   BULK COLLECT INTO EMP_TABLE;   

   FOR i IN EMP_TABLE.FIRST .. EMP_TABLE.LAST
   LOOP
      DBMS_OUTPUT.PUT_LINE('Ename = ' || EMP_TABLE(i) );
   END LOOP;
END DSQL;
/


