CREATE OR REPLACE PROCEDURE err_b
IS
   my_error   EXCEPTION;
BEGIN
   RAISE my_error;
EXCEPTION
   WHEN my_error
   THEN
      RAISE_APPLICATION_ERROR (-20001, 'Error in ERR_B');
END err_b;
/

CREATE OR REPLACE PROCEDURE err_a
IS
--   my_error EXCEPTION;
BEGIN
   err_b;
EXCEPTION
--   WHEN my_error
   WHEN OTHERS
   THEN
      DBMS_OUTPUT.PUT_LINE ('.');
      DBMS_OUTPUT.PUT_LINE ('. FORMAT_ERROR_STACK');
      DBMS_OUTPUT.PUT_LINE (DBMS_UTILITY.FORMAT_ERROR_STACK);
      DBMS_OUTPUT.PUT_LINE ('.');
      DBMS_OUTPUT.PUT_LINE ('. FORMAT_ERROR_BACKTRACE');
      DBMS_OUTPUT.PUT_LINE (DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
      DBMS_OUTPUT.PUT_LINE ('.');
      RAISE_APPLICATION_ERROR (-20000, 'Error in ERR_A');
END err_a;
/

execute err_a;
