

GRANT EXECUTE ON DBMS_ALERT TO &1;
GRANT CONNECT, RESOURCE,  QUERY REWRITE TO &1;
GRANT CREATE JOB TO &1;
GRANT CREATE TYPE TO &1; 
GRANT CREATE SESSION TO &1;
GRANT SELECT_CATALOG_ROLE TO &1;
GRANT EXECUTE ON UTL_FILE TO &1;
GRANT EXECUTE ON UTL_HTTP TO &1;
GRANT EXECUTE ON UTL_TCP TO &1;
GRANT EXECUTE ON DBMS_ALERT TO &1;
GRANT EXECUTE ON DBMS_DDL TO &1;
GRANT EXECUTE ON DBMS_JOB TO &1;
GRANT EXECUTE ON DBMS_LOB TO &1;
GRANT EXECUTE ON DBMS_LOCK TO &1;
GRANT EXECUTE ON DBMS_OUTPUT TO &1;
GRANT EXECUTE ON DBMS_PIPE TO &1;
GRANT EXECUTE ON DBMS_RANDOM TO &1;
GRANT EXECUTE ON DBMS_REFRESH TO &1;
GRANT EXECUTE ON DBMS_SESSION TO &1;
GRANT EXECUTE ON DBMS_SNAPSHOT TO &1;
GRANT EXECUTE ON DBMS_SQL TO &1;
GRANT EXECUTE ON DBMS_STATS TO &1;
GRANT EXECUTE ON DBMS_UTILITY TO &1;
GRANT ALTER SESSION to &1;
grant create any table to &1;

grant unlimited tablespace to &1;

alter user Student01 profile &1;


